server:
  port: 9321

spring:
  datasource:
    url: jdbc:mysql://47.109.52.178:3306/flea_market?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.twShop.model.entity

